version: "3"

networks:
   loki:
   prometheus:

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-size: "10m"

x-deploy:
  &default-deploy
  resources:
    limits:
      memory: 500m

services:
  app-python:
    image: rmoll/moscow_time_web_app:latest
    volumes:
      - ./python-data:/app/data
    ports:
      - target: 8080
        published: 8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging: *default-logging
    deploy: *default-deploy
    networks:
      - prometheus

  app_go:
    image: rmoll/moscow_time_web_app_go:latest
    volumes:
      - ./logs:/app/logs
      - ./go-data:/app/data
    ports:
      - target: 8081
        published: 8081
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging: *default-logging
    deploy: *default-deploy
    networks:
      - prometheus

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
    deploy: *default-deploy
    networks:
      - prometheus
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    logging: *default-logging
    deploy: *default-deploy
    networks:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prometheus
    logging: *default-logging
    deploy: *default-deploy

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana_ds.yml:/etc/grafana/provisioning/datasources/ds.yaml
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    logging: *default-logging
    deploy: *default-deploy
    networks:
      - prometheus
      - loki
