global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: 'app-python'
    static_configs:
      - targets: [ 'app-python:8080' ]
    metrics_path: '/metrics'

  - job_name: 'app_go'
    static_configs:
      - targets: [ 'app_go:8081' ]
    metrics_path: '/metrics'
