apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moscow-time-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: app.python
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: moscow-time-service-python
            port:
              number: 8080
  - host: app.go
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: moscow-time-service-go
              port:
                number: 8081
