apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time-web-app-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time-go
  template:
    metadata:
      labels:
        app: moscow-time-go
        lang: golang
    spec:
      containers:
      - name: moscow-time-go
        image: rmoll/moscow_time_web_app_go:latest
        ports:
        - containerPort: 8081
